default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: testguru_developement

test:
  <<: *default
  database: testguru_test

production:
  <<: *default
  database: testguru_production
